/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elgc_view;


import elgc_tools.Util;
import elgc_dao.Elgc_Gruposalgado_DAO;
import elgc_bean.ElgcGruposalgado;
        /**
 *
 * @author Lenovo
 */
public class JDlg_elgcGruposalgadoIA extends javax.swing.JDialog {

    ElgcGruposalgado elgcGruposalgado;
    Elgc_Gruposalgado_DAO elgcGruposalgado_DAO;
    /**
     * Creates new form JDlgc_elgcGrupoIA
     */
    public JDlg_elgcGruposalgadoIA(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("GRUPO DE SALGADOS");
        
        elgcGruposalgado_DAO = new Elgc_Gruposalgado_DAO();
    }
    
     public ElgcGruposalgado viewBean() {
        elgcGruposalgado = new ElgcGruposalgado();
        
        elgcGruposalgado.setIdelgcGruposalgado(Util.strInt(jTxtElgcCodigo.getText()));
        elgcGruposalgado.setElgcTiposalgado(jTxtElgcTiposalgado.getText());
        elgcGruposalgado.setElgcTipomassa(jTxtElgcTipomassa.getText());
        elgcGruposalgado.setElgcTipocozimento(jTxtElgcTipocozimento.getText());
        elgcGruposalgado.setElgcRecheio(jCboElgcRecheio.getSelectedIndex());
        elgcGruposalgado.setElgcQuantidade(Util.strDouble(jTxtElgcQuantidade.getText()));
        return elgcGruposalgado;
    }
     
     public void beanView(ElgcGruposalgado elgcGruposalgado){
        jTxtElgcCodigo.setText(Util.intStr(elgcGruposalgado.getIdelgcGruposalgado()));     
        jTxtElgcTiposalgado.setText(elgcGruposalgado.getElgcTiposalgado());
        jTxtElgcTipomassa.setText(elgcGruposalgado.getElgcTipomassa());
        jTxtElgcTipocozimento.setText(elgcGruposalgado.getElgcTipocozimento());
        jCboElgcRecheio.setSelectedIndex(elgcGruposalgado.getElgcRecheio());
        jTxtElgcQuantidade.setText(Util.doubleStr(elgcGruposalgado.getElgcQuantidade()));
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jBtnElgcIncluir = new javax.swing.JButton();
        jBtnElgcExcluir = new javax.swing.JButton();
        jBtnElgcAlterar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtElgcCodigo = new javax.swing.JTextField();
        jTxtElgcTipocozimento = new javax.swing.JTextField();
        jTxtElgcTiposalgado = new javax.swing.JTextField();
        jTxtElgcTipomassa = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jBtnElgcOk = new javax.swing.JButton();
        jBtnElgcCancelar = new javax.swing.JButton();
        jCboElgcRecheio = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtElgcQuantidade = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 153, 255), new java.awt.Color(102, 153, 255), new java.awt.Color(102, 153, 255), new java.awt.Color(102, 153, 255)));

        jBtnElgcIncluir.setText("Incluir");
        jBtnElgcIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElgcIncluirActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnElgcIncluir);

        jBtnElgcExcluir.setText("Exlcuir");
        jBtnElgcExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElgcExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnElgcExcluir);

        jBtnElgcAlterar.setText("Alterar");
        jBtnElgcAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElgcAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnElgcAlterar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(102, 163, 194));

        jLabel1.setText("Código");

        jLabel2.setText("Tipo do Salgado");

        jLabel3.setText("Tipo de Massa");

        jLabel4.setText("Tipo de Cozimento");

        jLabel5.setText("Recheio");

        jTxtElgcCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtElgcCodigoActionPerformed(evt);
            }
        });

        jTxtElgcTipocozimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtElgcTipocozimentoActionPerformed(evt);
            }
        });

        jTxtElgcTiposalgado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtElgcTiposalgadoActionPerformed(evt);
            }
        });

        jTxtElgcTipomassa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtElgcTipomassaActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 163, 194));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jBtnElgcOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elgc_imagens/ok.png"))); // NOI18N
        jBtnElgcOk.setText("Ok");
        jBtnElgcOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElgcOkActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnElgcOk);

        jBtnElgcCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elgc_imagens/cancelar.png"))); // NOI18N
        jBtnElgcCancelar.setText("Cancelar");
        jBtnElgcCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElgcCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnElgcCancelar);

        jCboElgcRecheio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Costela Desfiada", "Carne", "Italiano", "Moda da Casa", "Pizza", "Queijo", "Queridinho", "Romeu Julieta", "Banana Nevada", "Chocolate" }));

        jLabel17.setBackground(new java.awt.Color(102, 102, 255));
        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 255));
        jLabel17.setText("GRUPO");

        jLabel6.setText("Quantidade");

        jTxtElgcQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtElgcQuantidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCboElgcRecheio, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jTxtElgcQuantidade, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTxtElgcCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTxtElgcTipomassa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel5))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jTxtElgcTipocozimento, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jTxtElgcTiposalgado, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtElgcCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtElgcTiposalgado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtElgcTipomassa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtElgcTipocozimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCboElgcRecheio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtElgcQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnElgcIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElgcIncluirActionPerformed
       
    }//GEN-LAST:event_jBtnElgcIncluirActionPerformed

    private void jBtnElgcExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElgcExcluirActionPerformed
       
    }//GEN-LAST:event_jBtnElgcExcluirActionPerformed

    private void jBtnElgcAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElgcAlterarActionPerformed
        
    }//GEN-LAST:event_jBtnElgcAlterarActionPerformed

    private void jTxtElgcCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtElgcCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtElgcCodigoActionPerformed

    private void jTxtElgcTipocozimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtElgcTipocozimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtElgcTipocozimentoActionPerformed

    private void jTxtElgcTiposalgadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtElgcTiposalgadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtElgcTiposalgadoActionPerformed

    private void jTxtElgcTipomassaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtElgcTipomassaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtElgcTipomassaActionPerformed

    private void jBtnElgcOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElgcOkActionPerformed
        elgcGruposalgado = viewBean(); //elgcGruposalgado
        elgcGruposalgado_DAO = new Elgc_Gruposalgado_DAO();
        if (getTitle().toUpperCase().substring(0, 1).equals("I")) {
          elgcGruposalgado_DAO.insert(elgcGruposalgado);
        } else {            
          elgcGruposalgado_DAO.update(elgcGruposalgado);
        }
        setVisible(false);
    }//GEN-LAST:event_jBtnElgcOkActionPerformed

    private void jBtnElgcCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElgcCancelarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jBtnElgcCancelarActionPerformed

    private void jTxtElgcQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtElgcQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtElgcQuantidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlg_elgcGruposalgadoIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlg_elgcGruposalgadoIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlg_elgcGruposalgadoIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlg_elgcGruposalgadoIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlg_elgcGruposalgadoIA dialog = new JDlg_elgcGruposalgadoIA(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnElgcAlterar;
    private javax.swing.JButton jBtnElgcCancelar;
    private javax.swing.JButton jBtnElgcExcluir;
    private javax.swing.JButton jBtnElgcIncluir;
    private javax.swing.JButton jBtnElgcOk;
    private javax.swing.JComboBox<String> jCboElgcRecheio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtElgcCodigo;
    private javax.swing.JTextField jTxtElgcQuantidade;
    private javax.swing.JTextField jTxtElgcTipocozimento;
    private javax.swing.JTextField jTxtElgcTipomassa;
    private javax.swing.JTextField jTxtElgcTiposalgado;
    // End of variables declaration//GEN-END:variables
}
