/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elgc_view;

import elgc_tools.Util;
import elgc_bean.ElgcVendas;
import elgc_bean.ElgcCliente;
import elgc_bean.ElgcUsuarios;
import elgc_bean.ElgcVendasProduto;

import elgc_dao.Elgc_Vendas_DAO;
import elgc_dao.Elgc_Cliente_DAO;
import elgc_dao.Elgc_Usuarios_DAO;
import elgc_dao.Elgc_VendasProduto_DAO;

import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Lenovo
 */
public class JDlg_elgcVendas extends javax.swing.JDialog {

    public ElgcVendas elgcVendas;
    public Elgc_Vendas_DAO elgc_Vendas_DAO;
    public ElgcCliente elgcCliente;
    public Elgc_Cliente_DAO elgc_Cliente_DAO;
    public ElgcUsuarios elgcUsuarios;
    public Elgc_Usuarios_DAO elgc_Usuarios_DAO;
    public ElgcVendasProduto elgcVendasProduto;
    public Elgc_VendasProduto_DAO elgc_VendasProduto_DAO;
    public Elgc_VendasProdutoControle elgc_VendasProdutoControle;
    public JDlg_elgcVendasProduto jDlg_elgcVendasProduto;
    public JDlg_elgcVendas jDlg_elgcVendas;

    MaskFormatter mascaraDataVenda;
    private boolean incluindo;

    /**
     * Creates new form Jdlg_elgcVendas
     */
    public JDlg_elgcVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("MOVIMENTO");

        Util.habilitar(false, jFmtElgcDataVenda, jBtnElgcAlterar, jBtnElgcExcluir, jTxtElgcNumvendas, jTxtElgcData, jCboElgcCliente, jCboElgcUsuario, jTxtElgcTotal, jBtnElgcConfirmar, jBtnElgcCancelar, jBtnElgcIncluirIMG, JBtnElgcAlterarIMG, JBtnElgcExcluirIMG, jTable1);
        Util.habilitar(true, jBtnElgcIncluir, jBtnElgcPesquisar);

        try {
            mascaraDataVenda = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(JDlg_elgcVendas.class.getName()).log(Level.SEVERE, null, ex);
        }

        jFmtElgcDataVenda.setFormatterFactory(new DefaultFormatterFactory(mascaraDataVenda));

        elgcVendas = new ElgcVendas();
        elgc_Vendas_DAO = new Elgc_Vendas_DAO();
        elgc_VendasProduto_DAO = new Elgc_VendasProduto_DAO();

        List lista = new ArrayList();
        elgc_VendasProdutoControle = new Elgc_VendasProdutoControle();
        elgc_VendasProdutoControle.setList(lista);
        jTable1.setModel(elgc_VendasProdutoControle);

        elgc_Cliente_DAO = new Elgc_Cliente_DAO();
        List listaElgcCliente = elgc_Cliente_DAO.listAll();
        for (int i = 0; i < listaElgcCliente.size(); i++) {
            elgcCliente = (ElgcCliente) listaElgcCliente.get(i);
            jCboElgcCliente.addItem(elgcCliente);
        }

        elgc_Usuarios_DAO = new Elgc_Usuarios_DAO();
        List listaElgcUsuarios = elgc_Usuarios_DAO.listAll();
        for (int i = 0; i < listaElgcUsuarios.size(); i++) {
            elgcUsuarios = (ElgcUsuarios) listaElgcUsuarios.get(i);
            jCboElgcUsuario.addItem(elgcUsuarios);
        }
    }

    public ElgcVendas viewBean() {

        elgcVendas = new ElgcVendas();

        elgcVendas.setIdelgcVendas(Util.strInt(jTxtElgcNumvendas.getText()));

        elgcVendas.setElgcCliente((ElgcCliente) jCboElgcUsuario.getSelectedItem());
        elgcVendas.setElgcUsuarios((ElgcUsuarios) jCboElgcCliente.getSelectedItem());
        elgcVendas.setElgcDataVenda(Util.strDate(jFmtElgcDataVenda.getText()));
        elgcVendas.setElgcValortotalVenda(Util.strDouble(jTxtElgcTotal.getText()));

        return elgcVendas;

    }

    public void beanView(ElgcVendas elgcVendas) {

        jTxtElgcNumvendas.setText(Util.intStr(elgcVendas.getIdelgcVendas()));
        jCboElgcUsuario.setSelectedItem(elgcVendas.getElgcUsuarios());
        jCboElgcCliente.setSelectedItem((elgcVendas.getElgcCliente()));
        jFmtElgcDataVenda.setText(Util.datestr(elgcVendas.getElgcDataVenda()));
        jTxtElgcTotal.setText(Util.doubleStr(elgcVendas.getElgcValortotalVenda()));

        elgc_VendasProduto_DAO = new Elgc_VendasProduto_DAO();
        List listaProdutos = (List) elgc_VendasProduto_DAO.listProdutos(elgcVendas);

        elgc_VendasProdutoControle.setList(listaProdutos);

    }

    public int getSelectedRowProd() {
        return jTable1.getSelectedRow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTxtElgcData = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtElgcNumvendas = new javax.swing.JTextField();
        jCboElgcUsuario = new javax.swing.JComboBox<ElgcUsuarios>();
        jCboElgcCliente = new javax.swing.JComboBox<ElgcCliente>();
        jTxtElgcTotal = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JBtnElgcAlterarIMG = new javax.swing.JButton();
        JBtnElgcExcluirIMG = new javax.swing.JButton();
        jBtnElgcIncluirIMG = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jBtnElgcIncluir = new javax.swing.JButton();
        jBtnElgcCancelar = new javax.swing.JButton();
        jBtnElgcPesquisar = new javax.swing.JButton();
        jBtnElgcConfirmar = new javax.swing.JButton();
        jBtnElgcExcluir = new javax.swing.JButton();
        jBtnElgcAlterar = new javax.swing.JButton();
        jFmtElgcDataVenda = new javax.swing.JFormattedTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("jButton1");

        jButton3.setText("jButton1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Num. Vendas");

        jLabel3.setText("Data da venda");

        jLabel4.setText("Usuário");

        jLabel5.setText("Cliente");

        jLabel6.setText("Total");

        jCboElgcUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboElgcUsuarioActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Produto", "Quantidade", "Valor Unitário", "Total"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        JBtnElgcAlterarIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elgc_imagens/alterar.png"))); // NOI18N
        JBtnElgcAlterarIMG.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        JBtnElgcAlterarIMG.setMaximumSize(new java.awt.Dimension(70, 70));
        JBtnElgcAlterarIMG.setMinimumSize(new java.awt.Dimension(70, 70));
        JBtnElgcAlterarIMG.setPreferredSize(new java.awt.Dimension(70, 70));
        JBtnElgcAlterarIMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnElgcAlterarIMGActionPerformed(evt);
            }
        });

        JBtnElgcExcluirIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elgc_imagens/Excluir.png"))); // NOI18N
        JBtnElgcExcluirIMG.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.red, java.awt.Color.red, java.awt.Color.red, java.awt.Color.red));
        JBtnElgcExcluirIMG.setMaximumSize(new java.awt.Dimension(70, 70));
        JBtnElgcExcluirIMG.setMinimumSize(new java.awt.Dimension(70, 70));
        JBtnElgcExcluirIMG.setPreferredSize(new java.awt.Dimension(70, 70));
        JBtnElgcExcluirIMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnElgcExcluirIMGActionPerformed(evt);
            }
        });

        jBtnElgcIncluirIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elgc_imagens/incluir.png"))); // NOI18N
        jBtnElgcIncluirIMG.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255)));
        jBtnElgcIncluirIMG.setMaximumSize(new java.awt.Dimension(70, 70));
        jBtnElgcIncluirIMG.setMinimumSize(new java.awt.Dimension(70, 70));
        jBtnElgcIncluirIMG.setPreferredSize(new java.awt.Dimension(70, 70));
        jBtnElgcIncluirIMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElgcIncluirIMGActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.black, java.awt.Color.black, java.awt.Color.darkGray));

        jBtnElgcIncluir.setText("Incluir");
        jBtnElgcIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElgcIncluirActionPerformed(evt);
            }
        });

        jBtnElgcCancelar.setText("Cancelar");
        jBtnElgcCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElgcCancelarActionPerformed(evt);
            }
        });

        jBtnElgcPesquisar.setText("Pesquisar");
        jBtnElgcPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElgcPesquisarActionPerformed(evt);
            }
        });

        jBtnElgcConfirmar.setText("Confirmar");
        jBtnElgcConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElgcConfirmarActionPerformed(evt);
            }
        });

        jBtnElgcExcluir.setText("Excluir");
        jBtnElgcExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElgcExcluirActionPerformed(evt);
            }
        });

        jBtnElgcAlterar.setText("Alterar");
        jBtnElgcAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElgcAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnElgcIncluir)
                .addGap(14, 14, 14)
                .addComponent(jBtnElgcAlterar)
                .addGap(18, 18, 18)
                .addComponent(jBtnElgcExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnElgcConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnElgcCancelar)
                .addGap(18, 18, 18)
                .addComponent(jBtnElgcPesquisar)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnElgcIncluir)
                    .addComponent(jBtnElgcPesquisar)
                    .addComponent(jBtnElgcCancelar)
                    .addComponent(jBtnElgcConfirmar)
                    .addComponent(jBtnElgcExcluir)
                    .addComponent(jBtnElgcAlterar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jFmtElgcDataVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtElgcDataVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTxtElgcNumvendas, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFmtElgcDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jCboElgcUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCboElgcCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTxtElgcTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBtnElgcAlterarIMG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBtnElgcExcluirIMG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jBtnElgcIncluirIMG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 11, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel2)
                    .addContainerGap(744, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtElgcNumvendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCboElgcUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCboElgcCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtElgcTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtElgcDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jBtnElgcIncluirIMG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBtnElgcAlterarIMG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(JBtnElgcExcluirIMG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel2)
                    .addContainerGap(473, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnElgcIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElgcIncluirActionPerformed
        Util.habilitar(true, jBtnElgcConfirmar, jBtnElgcCancelar, jFmtElgcDataVenda, jTxtElgcNumvendas, jTxtElgcData, jCboElgcCliente, jCboElgcUsuario, jTxtElgcTotal, jBtnElgcIncluirIMG, JBtnElgcAlterarIMG, JBtnElgcExcluirIMG, jTable1);
        Util.habilitar(false, jBtnElgcIncluir, jBtnElgcAlterar, jBtnElgcExcluir, jBtnElgcPesquisar);
        Util.limparCampos(jTxtElgcNumvendas, jCboElgcUsuario, jFmtElgcDataVenda, jCboElgcCliente, jTxtElgcTotal);

        elgc_VendasProdutoControle.setList(new ArrayList());
        jTxtElgcNumvendas.grabFocus();
        incluindo = true;
        elgcVendas = new ElgcVendas();
    }//GEN-LAST:event_jBtnElgcIncluirActionPerformed

    private void jBtnElgcCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElgcCancelarActionPerformed
        Util.habilitar(false, jTxtElgcNumvendas,jBtnElgcAlterar, jBtnElgcExcluir, jTxtElgcData, jCboElgcCliente, jCboElgcUsuario, jTxtElgcTotal, jBtnElgcConfirmar, jBtnElgcCancelar, jBtnElgcIncluirIMG, JBtnElgcAlterarIMG, JBtnElgcExcluirIMG, jTable1);
        Util.habilitar(true, jBtnElgcIncluir,  jBtnElgcPesquisar);
        Util.limparCampos(jTxtElgcNumvendas, jCboElgcUsuario, jFmtElgcDataVenda, jCboElgcCliente, jTxtElgcTotal, jTable1);
        elgc_VendasProdutoControle.setList(new ArrayList());

    }//GEN-LAST:event_jBtnElgcCancelarActionPerformed

    private void jBtnElgcPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElgcPesquisarActionPerformed
        Util.habilitar(true, jFmtElgcDataVenda, jBtnElgcPesquisar, jBtnElgcAlterar, jBtnElgcExcluir, jTxtElgcNumvendas, jTxtElgcData, jCboElgcCliente, jCboElgcUsuario, jTxtElgcTotal, jBtnElgcCancelar, jBtnElgcIncluirIMG, JBtnElgcAlterarIMG, JBtnElgcExcluirIMG, jTable1);
        Util.habilitar(false, jBtnElgcIncluir, jBtnElgcConfirmar);

        JDlg_elgcVendasPesquisar jDlg_elgcVendasPesquisar = new JDlg_elgcVendasPesquisar(null, true);
        jDlg_elgcVendasPesquisar.setTelaAnterior(this);
        jDlg_elgcVendasPesquisar.setVisible(true);
    }//GEN-LAST:event_jBtnElgcPesquisarActionPerformed

    private void jBtnElgcConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElgcConfirmarActionPerformed
        elgcVendas = viewBean();
        elgc_Vendas_DAO = new Elgc_Vendas_DAO();

        if (incluindo == true) {
            elgc_Vendas_DAO.insert(elgcVendas);
            elgc_VendasProduto_DAO = new Elgc_VendasProduto_DAO();
            ElgcVendasProduto elgcVendasProduto;
            for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                elgcVendasProduto = elgc_VendasProdutoControle.getBean(linha);
                elgcVendasProduto.setElgcVendas(elgcVendas);
                elgc_VendasProduto_DAO.insert(elgcVendasProduto);

            }

        } else {
            elgc_Vendas_DAO.update(elgcVendas);
            elgc_VendasProduto_DAO = new Elgc_VendasProduto_DAO();
            ElgcVendasProduto elgcVendasProduto;
            for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                elgcVendasProduto = elgc_VendasProdutoControle.getBean(linha);
                elgcVendasProduto.setElgcVendas(elgcVendas);
                elgc_VendasProduto_DAO.insert(elgcVendasProduto);
            }

            Util.habilitar(false, jBtnElgcExcluir, jBtnElgcIncluir, jBtnElgcAlterar, jBtnElgcAlterar);
            Util.limparCampos(jTxtElgcNumvendas, jCboElgcUsuario, jFmtElgcDataVenda, jCboElgcCliente, jTxtElgcTotal, jTable1);
            elgc_VendasProdutoControle.setList(new ArrayList());
        }
    }//GEN-LAST:event_jBtnElgcConfirmarActionPerformed

    private void jBtnElgcExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElgcExcluirActionPerformed
        if (elgcVendas != null) {
            if (Util.perguntar("Deseja excluir a Compra ?") == true) {
                elgc_VendasProduto_DAO = new Elgc_VendasProduto_DAO();
                ElgcVendasProduto elgcVendasProduto;
                for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                    elgcVendasProduto = elgc_VendasProdutoControle.getBean(linha);
                    elgc_VendasProduto_DAO.delete(elgcVendasProduto);
                }
                elgc_VendasProduto_DAO.delete(elgcVendas);

            }
        } else {
            Util.mensagem("Deve ser realizada uma pesquisa antes");
        }
        Util.limparCampos(jTxtElgcNumvendas, jCboElgcUsuario, jFmtElgcDataVenda, jCboElgcCliente, jTxtElgcTotal, jTable1);

    }//GEN-LAST:event_jBtnElgcExcluirActionPerformed

    private void jBtnElgcAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElgcAlterarActionPerformed
        Util.habilitar(false, jBtnElgcIncluir, jBtnElgcAlterar, jBtnElgcExcluir, jBtnElgcPesquisar);
        if (elgcVendas != null) {

            elgc_VendasProduto_DAO = new Elgc_VendasProduto_DAO();
            ElgcVendasProduto elgcVendasProduto;
            for (int linha = 0; linha < jTable1.getRowCount(); linha++) {
                elgcVendasProduto = elgc_VendasProdutoControle.getBean(linha);
                elgc_VendasProduto_DAO.delete(elgcVendasProduto);
            }

            Util.habilitar(true, jTxtElgcNumvendas, jTxtElgcData, jCboElgcCliente, jCboElgcUsuario, jTxtElgcTotal, jBtnElgcConfirmar, jBtnElgcCancelar, jBtnElgcIncluirIMG, JBtnElgcAlterarIMG, JBtnElgcExcluirIMG, jTable1);

        } else {
            Util.mensagem("Deve ser realizada uma pesquisa antes");
        }
        incluindo = false;
    }//GEN-LAST:event_jBtnElgcAlterarActionPerformed

    private void jCboElgcUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboElgcUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboElgcUsuarioActionPerformed

    private void jBtnElgcIncluirIMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElgcIncluirIMGActionPerformed
        jDlg_elgcVendasProduto = new JDlg_elgcVendasProduto(null, true);
        jDlg_elgcVendasProduto.setTitle("INCLUSÃO");
        jDlg_elgcVendasProduto.setTelaAnterior(this);
        jDlg_elgcVendasProduto.setVisible(true);
    }//GEN-LAST:event_jBtnElgcIncluirIMGActionPerformed

    private void jFmtElgcDataVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtElgcDataVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtElgcDataVendaActionPerformed

    private void JBtnElgcAlterarIMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnElgcAlterarIMGActionPerformed
        jDlg_elgcVendasProduto = new JDlg_elgcVendasProduto(null, true);
        jDlg_elgcVendasProduto.setTitle("ALTERAÇÃO");
        jDlg_elgcVendasProduto.setTelaAnterior(this);
        int linSel = jTable1.getSelectedRow();
        ElgcVendasProduto elgcVendasProduto = (ElgcVendasProduto) elgc_VendasProdutoControle.getBean(linSel);
        jDlg_elgcVendasProduto.beanView(elgcVendasProduto);
        jDlg_elgcVendasProduto.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_JBtnElgcAlterarIMGActionPerformed

    private void JBtnElgcExcluirIMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnElgcExcluirIMGActionPerformed
        if (getSelectedRowProd() == -1) {
            Util.mensagem("Nenhuma linha selecionada");
        } else {
            if (Util.perguntar("Confirmar exclusão do produto selecionado") == true) {
                elgc_VendasProdutoControle.removeBean(getSelectedRowProd());
            }
        }
    }//GEN-LAST:event_JBtnElgcExcluirIMGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlg_elgcVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlg_elgcVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlg_elgcVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlg_elgcVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlg_elgcVendas dialog = new JDlg_elgcVendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnElgcAlterarIMG;
    private javax.swing.JButton JBtnElgcExcluirIMG;
    private javax.swing.JButton jBtnElgcAlterar;
    private javax.swing.JButton jBtnElgcCancelar;
    private javax.swing.JButton jBtnElgcConfirmar;
    private javax.swing.JButton jBtnElgcExcluir;
    private javax.swing.JButton jBtnElgcIncluir;
    private javax.swing.JButton jBtnElgcIncluirIMG;
    private javax.swing.JButton jBtnElgcPesquisar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<ElgcCliente> jCboElgcCliente;
    private javax.swing.JComboBox<ElgcUsuarios> jCboElgcUsuario;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFormattedTextField jFmtElgcDataVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTxtElgcData;
    private javax.swing.JTextField jTxtElgcNumvendas;
    private javax.swing.JTextField jTxtElgcTotal;
    // End of variables declaration//GEN-END:variables
}
