/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elgc_view;

import elgc_bean.ElgcUsuarios;
import elgc_dao.Elgc_Usuarios_DAO;
import java.util.List;

/**
 *
 * @author Lenovo
 */
public class JDlg_elgcUsuariosPesquisar extends javax.swing.JDialog {

    private JDlg_elgcUsuarios jDlg_elgcUsuarios;
    Elgc_Usuarios_DAO elgc_Usuarios_DAO;
    Elgc_UsuariosControle elgc_UsuariosControle;
    /**
     * Creates new form JDlgUsuariosPesquisar
     */
    public JDlg_elgcUsuariosPesquisar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Consulta de usuário");
        
        elgc_UsuariosControle = new Elgc_UsuariosControle();
        elgc_Usuarios_DAO = new Elgc_Usuarios_DAO();
        List lista = elgc_Usuarios_DAO.listAll();
        elgc_UsuariosControle.setList(lista);
        jTable1.setModel(elgc_UsuariosControle);                
    }
    
    public void setTelaAnterior(JDlg_elgcUsuarios jDlg_elgcUsuarios) {
        this.jDlg_elgcUsuarios = jDlg_elgcUsuarios;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnElgcOk = new javax.swing.JButton();
        jBtnElgcCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jBtnElgcOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elgc_imagens/ok.png"))); // NOI18N
        jBtnElgcOk.setText("OK");
        jBtnElgcOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElgcOkActionPerformed(evt);
            }
        });

        jBtnElgcCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elgc_imagens/cancelar.png"))); // NOI18N
        jBtnElgcCancelar.setText("Cancelar");
        jBtnElgcCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElgcCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnElgcOk)
                .addGap(18, 18, 18)
                .addComponent(jBtnElgcCancelar)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnElgcOk)
                    .addComponent(jBtnElgcCancelar))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnElgcOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElgcOkActionPerformed
        // TODO add your handling code here:
        int rowSel = jTable1.getSelectedRow();
        ElgcUsuarios elgcUsuarios = elgc_UsuariosControle.getBean(rowSel);
        jDlg_elgcUsuarios.beanView(elgcUsuarios);
        setVisible(false);
    }//GEN-LAST:event_jBtnElgcOkActionPerformed

    private void jBtnElgcCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElgcCancelarActionPerformed
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnElgcCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlg_elgcUsuariosPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlg_elgcUsuariosPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlg_elgcUsuariosPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlg_elgcUsuariosPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlg_elgcUsuariosPesquisar dialog = new JDlg_elgcUsuariosPesquisar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnElgcCancelar;
    private javax.swing.JButton jBtnElgcOk;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
