/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elgc_view;
import elgc_query.JDlg_elgcConsultaCliente;
import elgc_query.JDlg_elgcConsultaUsuarios;
import elgc_query.JDlg_elgcConsultaGruposalgado;
import elgc_query.JDlg_elgcConsultaProduto;
import elgc_query.JDlg_elgcConsultaVendas;


/**
 *
 * @author u09894615139
 */
public class JFrmElgcPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JfrmPrincipal
     */
    public JFrmElgcPrincipal() {
        initComponents();
        setTitle("MENU");
        setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jBtnElgcClienteIMG = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jBtnElgcGrupoSalgadoIMG = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jBtnElgcProdutoIMG = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jBtnElgcUsuarioIMG = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jBtnElgcVendasIMG = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        jBtnElgcSairIMG = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuElgcCadastro = new javax.swing.JMenu();
        jMnuElgcCliente = new javax.swing.JMenuItem();
        jMnuElgcGrupo = new javax.swing.JMenuItem();
        jMnuElgcProduto = new javax.swing.JMenuItem();
        jMnuElgcUsuarios = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMnuSair = new javax.swing.JMenuItem();
        jMnuElgcMovimento = new javax.swing.JMenu();
        jMnuElgcVendas = new javax.swing.JMenuItem();
        jElgcConsulta = new javax.swing.JMenu();
        jMnuElgcConsultaUsuarios = new javax.swing.JMenuItem();
        jMnuElgcConsultaClientes = new javax.swing.JMenuItem();
        jMnuElgcConsultaGrupoSalgado = new javax.swing.JMenuItem();
        jMnuElgcConsultaProduto = new javax.swing.JMenuItem();
        jMnuElgcConsultaVendas = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jButton1.setText("jButton1");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jPanel1.setBackground(new java.awt.Color(102, 163, 194));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 163, 194));

        jToolBar1.setBackground(new java.awt.Color(102, 163, 194));
        jToolBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 163, 194), new java.awt.Color(102, 163, 194), new java.awt.Color(102, 163, 194), new java.awt.Color(102, 163, 194)));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator3);

        jBtnElgcClienteIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elgc_imagens/cliente.png"))); // NOI18N
        jBtnElgcClienteIMG.setFocusable(false);
        jBtnElgcClienteIMG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnElgcClienteIMG.setMaximumSize(new java.awt.Dimension(70, 45));
        jBtnElgcClienteIMG.setMinimumSize(new java.awt.Dimension(70, 45));
        jBtnElgcClienteIMG.setPreferredSize(new java.awt.Dimension(70, 45));
        jBtnElgcClienteIMG.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnElgcClienteIMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElgcClienteIMGActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnElgcClienteIMG);
        jToolBar1.add(jSeparator4);

        jBtnElgcGrupoSalgadoIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elgc_imagens/grupo.png"))); // NOI18N
        jBtnElgcGrupoSalgadoIMG.setFocusable(false);
        jBtnElgcGrupoSalgadoIMG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnElgcGrupoSalgadoIMG.setMaximumSize(new java.awt.Dimension(70, 45));
        jBtnElgcGrupoSalgadoIMG.setMinimumSize(new java.awt.Dimension(70, 45));
        jBtnElgcGrupoSalgadoIMG.setPreferredSize(new java.awt.Dimension(70, 45));
        jBtnElgcGrupoSalgadoIMG.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnElgcGrupoSalgadoIMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElgcGrupoSalgadoIMGActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnElgcGrupoSalgadoIMG);
        jToolBar1.add(jSeparator7);

        jBtnElgcProdutoIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elgc_imagens/produtos.png"))); // NOI18N
        jBtnElgcProdutoIMG.setFocusable(false);
        jBtnElgcProdutoIMG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnElgcProdutoIMG.setMaximumSize(new java.awt.Dimension(70, 45));
        jBtnElgcProdutoIMG.setMinimumSize(new java.awt.Dimension(70, 45));
        jBtnElgcProdutoIMG.setPreferredSize(new java.awt.Dimension(70, 45));
        jBtnElgcProdutoIMG.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnElgcProdutoIMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElgcProdutoIMGActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnElgcProdutoIMG);
        jToolBar1.add(jSeparator5);

        jBtnElgcUsuarioIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elgc_imagens/cliente.png"))); // NOI18N
        jBtnElgcUsuarioIMG.setFocusable(false);
        jBtnElgcUsuarioIMG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnElgcUsuarioIMG.setMaximumSize(new java.awt.Dimension(70, 45));
        jBtnElgcUsuarioIMG.setMinimumSize(new java.awt.Dimension(70, 45));
        jBtnElgcUsuarioIMG.setPreferredSize(new java.awt.Dimension(70, 45));
        jBtnElgcUsuarioIMG.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnElgcUsuarioIMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElgcUsuarioIMGActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnElgcUsuarioIMG);
        jToolBar1.add(jSeparator6);

        jBtnElgcVendasIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elgc_imagens/vendas.png"))); // NOI18N
        jBtnElgcVendasIMG.setFocusable(false);
        jBtnElgcVendasIMG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnElgcVendasIMG.setMaximumSize(new java.awt.Dimension(70, 45));
        jBtnElgcVendasIMG.setMinimumSize(new java.awt.Dimension(70, 45));
        jBtnElgcVendasIMG.setPreferredSize(new java.awt.Dimension(70, 45));
        jBtnElgcVendasIMG.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnElgcVendasIMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElgcVendasIMGActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnElgcVendasIMG);
        jToolBar1.add(jSeparator10);

        jBtnElgcSairIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elgc_imagens/sair.png"))); // NOI18N
        jBtnElgcSairIMG.setFocusable(false);
        jBtnElgcSairIMG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnElgcSairIMG.setMaximumSize(new java.awt.Dimension(70, 45));
        jBtnElgcSairIMG.setMinimumSize(new java.awt.Dimension(70, 45));
        jBtnElgcSairIMG.setPreferredSize(new java.awt.Dimension(70, 45));
        jBtnElgcSairIMG.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnElgcSairIMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElgcSairIMGActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnElgcSairIMG);
        jToolBar1.add(jSeparator8);

        jPanel2.setBackground(new java.awt.Color(102, 163, 194));

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255), new java.awt.Color(204, 204, 255)));

        jMnuElgcCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elgc_imagens/cadastro.png"))); // NOI18N
        jMnuElgcCadastro.setText("Cadastro");

        jMnuElgcCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMnuElgcCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elgc_imagens/cliente.png"))); // NOI18N
        jMnuElgcCliente.setText("Cliente");
        jMnuElgcCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuElgcClienteActionPerformed(evt);
            }
        });
        jMnuElgcCadastro.add(jMnuElgcCliente);

        jMnuElgcGrupo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMnuElgcGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elgc_imagens/grupo.png"))); // NOI18N
        jMnuElgcGrupo.setText("Grupo");
        jMnuElgcGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuElgcGrupoActionPerformed(evt);
            }
        });
        jMnuElgcCadastro.add(jMnuElgcGrupo);

        jMnuElgcProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMnuElgcProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elgc_imagens/produtos.png"))); // NOI18N
        jMnuElgcProduto.setText("Produto");
        jMnuElgcProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuElgcProdutoActionPerformed(evt);
            }
        });
        jMnuElgcCadastro.add(jMnuElgcProduto);

        jMnuElgcUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnuElgcUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elgc_imagens/usuario.png"))); // NOI18N
        jMnuElgcUsuarios.setText("Usuarios");
        jMnuElgcUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuElgcUsuariosActionPerformed(evt);
            }
        });
        jMnuElgcCadastro.add(jMnuElgcUsuarios);
        jMnuElgcCadastro.add(jSeparator2);

        jMnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elgc_imagens/sair.png"))); // NOI18N
        jMnuSair.setText("Sair");
        jMnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuSairActionPerformed(evt);
            }
        });
        jMnuElgcCadastro.add(jMnuSair);

        jMenuBar1.add(jMnuElgcCadastro);

        jMnuElgcMovimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elgc_imagens/movimento.png"))); // NOI18N
        jMnuElgcMovimento.setText("Movimento");

        jMnuElgcVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMnuElgcVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elgc_imagens/vendas.png"))); // NOI18N
        jMnuElgcVendas.setText("Vendas");
        jMnuElgcVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuElgcVendasActionPerformed(evt);
            }
        });
        jMnuElgcMovimento.add(jMnuElgcVendas);

        jMenuBar1.add(jMnuElgcMovimento);

        jElgcConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elgc_imagens/pesquisarlupa.png"))); // NOI18N
        jElgcConsulta.setText("Consultas");

        jMnuElgcConsultaUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMnuElgcConsultaUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elgc_imagens/consultapessoa.png"))); // NOI18N
        jMnuElgcConsultaUsuarios.setText("Consulta de Usuários");
        jMnuElgcConsultaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuElgcConsultaUsuariosActionPerformed(evt);
            }
        });
        jElgcConsulta.add(jMnuElgcConsultaUsuarios);

        jMnuElgcConsultaClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMnuElgcConsultaClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elgc_imagens/consultacaneta.png"))); // NOI18N
        jMnuElgcConsultaClientes.setText("Consulta de Clientes");
        jMnuElgcConsultaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuElgcConsultaClientesActionPerformed(evt);
            }
        });
        jElgcConsulta.add(jMnuElgcConsultaClientes);

        jMnuElgcConsultaGrupoSalgado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMnuElgcConsultaGrupoSalgado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elgc_imagens/consultatexto.png"))); // NOI18N
        jMnuElgcConsultaGrupoSalgado.setText("Consulta de Grupo");
        jMnuElgcConsultaGrupoSalgado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuElgcConsultaGrupoSalgadoActionPerformed(evt);
            }
        });
        jElgcConsulta.add(jMnuElgcConsultaGrupoSalgado);

        jMnuElgcConsultaProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMnuElgcConsultaProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elgc_imagens/consultaprod.png"))); // NOI18N
        jMnuElgcConsultaProduto.setText("Consulta de Produto");
        jMnuElgcConsultaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuElgcConsultaProdutoActionPerformed(evt);
            }
        });
        jElgcConsulta.add(jMnuElgcConsultaProduto);

        jMnuElgcConsultaVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMnuElgcConsultaVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/elgc_imagens/consultavendas.png"))); // NOI18N
        jMnuElgcConsultaVendas.setText("Consulta de Vendas");
        jMnuElgcConsultaVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuElgcConsultaVendasActionPerformed(evt);
            }
        });
        jElgcConsulta.add(jMnuElgcConsultaVendas);

        jMenuBar1.add(jElgcConsulta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuElgcClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuElgcClienteActionPerformed
        JDlg_elgcCliente jDlg_elgcCliente = new JDlg_elgcCliente(null, true);
        jDlg_elgcCliente.setVisible(true);
        
    }//GEN-LAST:event_jMnuElgcClienteActionPerformed

    private void jMnuElgcUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuElgcUsuariosActionPerformed
JDlg_elgcUsuarios jDlg_elgcUsuarios = new JDlg_elgcUsuarios(null,true);
jDlg_elgcUsuarios.setVisible(true);

    }//GEN-LAST:event_jMnuElgcUsuariosActionPerformed

    private void jMnuElgcGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuElgcGrupoActionPerformed
JDlg_elgcGruposalgado jDlg_elgcGruposalgado = new JDlg_elgcGruposalgado(null, true);
jDlg_elgcGruposalgado.setVisible(true);

    }//GEN-LAST:event_jMnuElgcGrupoActionPerformed

    private void jMnuElgcProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuElgcProdutoActionPerformed
JDlg_elgcProduto jDlg_elgcProduto = new JDlg_elgcProduto(null,true);
jDlg_elgcProduto.setVisible(true);

    }//GEN-LAST:event_jMnuElgcProdutoActionPerformed

    private void jMnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSairActionPerformed
System.exit(0);
    }//GEN-LAST:event_jMnuSairActionPerformed

    private void jMnuElgcVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuElgcVendasActionPerformed
JDlg_elgcVendas jDlg_elgcVendas = new JDlg_elgcVendas(null, true);
jDlg_elgcVendas.setVisible(true);
    }//GEN-LAST:event_jMnuElgcVendasActionPerformed

    private void jBtnElgcClienteIMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElgcClienteIMGActionPerformed
        JDlg_elgcCliente jDlg_elgcCliente = new JDlg_elgcCliente(null, true);
        jDlg_elgcCliente.setVisible(true);   
        
    }//GEN-LAST:event_jBtnElgcClienteIMGActionPerformed

    private void jBtnElgcGrupoSalgadoIMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElgcGrupoSalgadoIMGActionPerformed
JDlg_elgcGruposalgado jDlg_elgcGruposalgado = new JDlg_elgcGruposalgado(null, true);
jDlg_elgcGruposalgado.setVisible(true);

    }//GEN-LAST:event_jBtnElgcGrupoSalgadoIMGActionPerformed

    private void jBtnElgcProdutoIMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElgcProdutoIMGActionPerformed
JDlg_elgcProduto jDlg_elgcProduto = new JDlg_elgcProduto(null,true);
jDlg_elgcProduto.setVisible(true);

    }//GEN-LAST:event_jBtnElgcProdutoIMGActionPerformed

    private void jBtnElgcUsuarioIMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElgcUsuarioIMGActionPerformed
JDlg_elgcUsuarios jDlg_elgcUsuarios = new JDlg_elgcUsuarios(null,true);
jDlg_elgcUsuarios.setVisible(true);

    }//GEN-LAST:event_jBtnElgcUsuarioIMGActionPerformed

    private void jBtnElgcSairIMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElgcSairIMGActionPerformed
System.exit(0);
    }//GEN-LAST:event_jBtnElgcSairIMGActionPerformed

    private void jBtnElgcVendasIMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElgcVendasIMGActionPerformed
JDlg_elgcVendas jDlg_elgcVendas = new JDlg_elgcVendas(null, true);
jDlg_elgcVendas.setVisible(true);
    }//GEN-LAST:event_jBtnElgcVendasIMGActionPerformed

    private void jMnuElgcConsultaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuElgcConsultaUsuariosActionPerformed
 JDlg_elgcConsultaUsuarios jDlg_elgcConsultaUsuarios = new JDlg_elgcConsultaUsuarios(null,true);
 jDlg_elgcConsultaUsuarios.setVisible(true);

    }//GEN-LAST:event_jMnuElgcConsultaUsuariosActionPerformed

    private void jMnuElgcConsultaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuElgcConsultaClientesActionPerformed
JDlg_elgcConsultaCliente jDlg_elgcConsultaCliente = new JDlg_elgcConsultaCliente(null, true);
jDlg_elgcConsultaCliente.setVisible(true);

    }//GEN-LAST:event_jMnuElgcConsultaClientesActionPerformed

    private void jMnuElgcConsultaVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuElgcConsultaVendasActionPerformed
JDlg_elgcConsultaVendas jDlg_elgcConsultaVendas = new JDlg_elgcConsultaVendas(null, true);
jDlg_elgcConsultaVendas.setVisible(true);

    }//GEN-LAST:event_jMnuElgcConsultaVendasActionPerformed

    private void jMnuElgcConsultaGrupoSalgadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuElgcConsultaGrupoSalgadoActionPerformed
JDlg_elgcConsultaGruposalgado jDlg_elgcConsultaGruposalgado = new JDlg_elgcConsultaGruposalgado(null, true);
jDlg_elgcConsultaGruposalgado.setVisible(true);

    }//GEN-LAST:event_jMnuElgcConsultaGrupoSalgadoActionPerformed

    private void jMnuElgcConsultaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuElgcConsultaProdutoActionPerformed
JDlg_elgcConsultaProduto jDlg_elgcConsultaProduto = new JDlg_elgcConsultaProduto(null, true);
jDlg_elgcConsultaProduto.setVisible(true);

    }//GEN-LAST:event_jMnuElgcConsultaProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmElgcPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmElgcPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmElgcPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmElgcPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmElgcPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnElgcClienteIMG;
    private javax.swing.JButton jBtnElgcGrupoSalgadoIMG;
    private javax.swing.JButton jBtnElgcProdutoIMG;
    private javax.swing.JButton jBtnElgcSairIMG;
    private javax.swing.JButton jBtnElgcUsuarioIMG;
    private javax.swing.JButton jBtnElgcVendasIMG;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jElgcConsulta;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMnuElgcCadastro;
    private javax.swing.JMenuItem jMnuElgcCliente;
    private javax.swing.JMenuItem jMnuElgcConsultaClientes;
    private javax.swing.JMenuItem jMnuElgcConsultaGrupoSalgado;
    private javax.swing.JMenuItem jMnuElgcConsultaProduto;
    private javax.swing.JMenuItem jMnuElgcConsultaUsuarios;
    private javax.swing.JMenuItem jMnuElgcConsultaVendas;
    private javax.swing.JMenuItem jMnuElgcGrupo;
    private javax.swing.JMenu jMnuElgcMovimento;
    private javax.swing.JMenuItem jMnuElgcProduto;
    private javax.swing.JMenuItem jMnuElgcUsuarios;
    private javax.swing.JMenuItem jMnuElgcVendas;
    private javax.swing.JMenuItem jMnuSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
