/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elgc_query;

import elgc_dao.Elgc_Cliente_DAO;
import elgc_bean.ElgcCliente;
import elgc_tools.Util;
import java.util.List;
import elgc_view.Elgc_ClienteControle;
import elgc_view.JDlg_elgcCliente;
import java.util.Date;

/**
 *
 * @author Lenovo
 */
public class JDlg_elgcConsultaCliente extends javax.swing.JDialog {

    ElgcCliente elgcCliente;
    Elgc_Cliente_DAO elgc_Cliente_DAO;
    Elgc_ClienteControle elgc_ClienteControle;

    public JDlg_elgcConsultaCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("CONSULTA CLIENTE");
        
        elgc_ClienteControle = new Elgc_ClienteControle();
        elgc_Cliente_DAO = new Elgc_Cliente_DAO();
        List lista = elgc_Cliente_DAO.listAll();
        elgc_ClienteControle.setList(lista);
        jELGCTable.setModel(elgc_ClienteControle);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtElgcDataNasc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jELGCTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jBtnElgcConsultar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtElgcNome = new javax.swing.JTextField();
        jFmtElgcDatNasc = new javax.swing.JFormattedTextField();

        jTxtElgcDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtElgcDataNascActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jELGCTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jELGCTable);

        jPanel1.setBackground(new java.awt.Color(102, 163, 194));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jBtnElgcConsultar.setBackground(new java.awt.Color(204, 204, 255));
        jBtnElgcConsultar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jBtnElgcConsultar.setForeground(new java.awt.Color(204, 204, 255));
        jBtnElgcConsultar.setText("CONSULTAR");
        jBtnElgcConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElgcConsultarActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data de Nascimento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTxtElgcNome, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jFmtElgcDatNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(jBtnElgcConsultar)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnElgcConsultar)
                    .addComponent(jTxtElgcNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtElgcDatNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnElgcConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElgcConsultarActionPerformed
        // Verifica se ambos os campos de texto (nome e data de nascimento) estão vazios.
        if (jTxtElgcNome.getText().equals("") && jFmtElgcDatNasc.getText().equals("")) {
            // Se ambos estiverem vazios, obtém a lista completa de clientes e a define no controle.
            List lista = elgc_Cliente_DAO.listAll();
            elgc_ClienteControle.setList(lista);
        } else {
            // Caso pelo menos um dos campos não esteja vazio.

            // Verifica se ambos os campos (nome e data de nascimento) têm valores.
            if (!jTxtElgcNome.getText().equals("") && !jFmtElgcDatNasc.getText().equals("")) {
                // Se ambos tiverem valores, obtém a lista filtrada por nome e data de nascimento.
                Date data = Util.strDate(jFmtElgcDatNasc.getText());
                List lista = elgc_Cliente_DAO.listNomeData(jTxtElgcNome.getText(), data);
                elgc_ClienteControle.setList(lista);
            } else {
                // Se apenas um dos campos tem valor.

                // Verifica se o campo de nome não está vazio.
                if (!jTxtElgcNome.getText().equals("")) {
                    // Se o campo de nome tiver valor, obtém a lista filtrada por nome.
                    List lista = elgc_Cliente_DAO.listNome(jTxtElgcNome.getText());
                    elgc_ClienteControle.setList(lista);
                } else {
                    // Se apenas o campo de data de nascimento tem valor.

                    // Verifica se o campo de data de nascimento não está vazio.
                    if (!jFmtElgcDatNasc.getText().equals("")) {
                        // Se o campo de data de nascimento tiver valor, converte a data e obtém a lista filtrada por data.
                        Date data = Util.strDate(jFmtElgcDatNasc.getText());
                        List lista = elgc_Cliente_DAO.listData(data);
                        elgc_ClienteControle.setList(lista);
                    }
                }
            }
        }

    }//GEN-LAST:event_jBtnElgcConsultarActionPerformed

    private void jTxtElgcDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtElgcDataNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtElgcDataNascActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlg_elgcConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlg_elgcConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlg_elgcConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlg_elgcConsultaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlg_elgcConsultaCliente dialog = new JDlg_elgcConsultaCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnElgcConsultar;
    private javax.swing.JTable jELGCTable;
    private javax.swing.JFormattedTextField jFmtElgcDatNasc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtElgcDataNasc;
    private javax.swing.JTextField jTxtElgcNome;
    // End of variables declaration//GEN-END:variables
}
