/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elgc_query;
import elgc_bean.ElgcProduto;
import elgc_dao.Elgc_Produto_DAO;
import elgc_tools.Util;
import java.util.List;
import elgc_view.Elgc_ProdutoController;

/**
 *
 * @author Lenovo
 */
public class JDlg_elgcConsultaProduto extends javax.swing.JDialog {

    private ElgcProduto elgcProduto;
    Elgc_Produto_DAO elgc_Produto_DAO;
    Elgc_ProdutoController elgc_ProdutoController;

    public JDlg_elgcConsultaProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("CONSULTA PRODUTO");

        elgc_ProdutoController = new Elgc_ProdutoController();
        elgc_Produto_DAO = new Elgc_Produto_DAO();
        List lista = elgc_Produto_DAO.listAll();
        elgc_ProdutoController.setList(lista);
        jELGCTable.setModel(elgc_ProdutoController);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtElgcNomeProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtElgcValorUni = new javax.swing.JTextField();
        jBtnElgcConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jELGCTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 163, 194));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome do Produto");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Valor Unitário");

        jBtnElgcConsultar.setBackground(new java.awt.Color(204, 204, 255));
        jBtnElgcConsultar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jBtnElgcConsultar.setForeground(new java.awt.Color(204, 204, 255));
        jBtnElgcConsultar.setText("CONSULTAR");
        jBtnElgcConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElgcConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTxtElgcNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTxtElgcValorUni, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addComponent(jBtnElgcConsultar)
                        .addGap(36, 36, 36))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtElgcNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtElgcValorUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnElgcConsultar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jELGCTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jELGCTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnElgcConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElgcConsultarActionPerformed
        // Verifica se ambos os campos de nome do produto e valor unitário estão vazios
        if (jTxtElgcNomeProduto.getText().equals("") && jTxtElgcValorUni.getText().equals("")) {
            // Se ambos estiverem vazios, lista todos os produtos
            List lista = elgc_Produto_DAO.listAll();
            elgc_ProdutoController.setList(lista);
        } else {
            // Verifica se ambos os campos de nome do produto e valor unitário não estão vazios
            if (!jTxtElgcNomeProduto.getText().equals("") && !jTxtElgcValorUni.getText().equals("")) {
                // Se ambos não estiverem vazios, filtra por nome do produto e valor unitário
                List lista = elgc_Produto_DAO.listProdutoValor(jTxtElgcNomeProduto.getText(), Util.strDouble(jTxtElgcValorUni.getText()));
                elgc_ProdutoController.setList(lista);
            } else {
                // Verifica se apenas o campo de nome do produto está vazio
                if (jTxtElgcNomeProduto.getText().equals("")) {
                    // Se apenas o campo de nome do produto estiver vazio, filtra apenas por valor unitário
                    List lista = elgc_Produto_DAO.listProduto(jTxtElgcNomeProduto.getText());
                    elgc_ProdutoController.setList(lista);
                } else {
                    // Se nenhum dos casos anteriores for atendido e apenas o campo de valor unitário não estiver vazio, filtra apenas por nome do produto
                    if (!jTxtElgcValorUni.getText().equals("")) {
                    List lista = elgc_Produto_DAO.listValorUni(Util.strDouble(jTxtElgcValorUni.getText()));
                    elgc_ProdutoController.setList(lista);
                    }
                }
            }
        }

    }//GEN-LAST:event_jBtnElgcConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlg_elgcConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlg_elgcConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlg_elgcConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlg_elgcConsultaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlg_elgcConsultaProduto dialog = new JDlg_elgcConsultaProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnElgcConsultar;
    private javax.swing.JTable jELGCTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtElgcNomeProduto;
    private javax.swing.JTextField jTxtElgcValorUni;
    // End of variables declaration//GEN-END:variables
}
