/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package elgc_query;

import elgc_bean.ElgcVendas;
import elgc_dao.Elgc_Vendas_DAO;
import elgc_tools.Util;
import elgc_view.Elgc_VendasControle;
import java.util.Date;
import java.util.List;

/**
 *
 * @author Lenovo
 */
public class JDlg_elgcConsultaVendas extends javax.swing.JDialog {

    public ElgcVendas elgcVendas;
    public Elgc_Vendas_DAO elgc_Vendas_DAO;
    Elgc_VendasControle elgc_VendasControle;

    public JDlg_elgcConsultaVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("CONSULTA VENDAS");

        elgc_Vendas_DAO = new Elgc_Vendas_DAO();
        elgc_VendasControle = new Elgc_VendasControle();
        List lista = elgc_Vendas_DAO.listAll();
        elgc_VendasControle.setList(lista);
        jELGCTable.setModel(elgc_VendasControle);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtElgcDataV = new javax.swing.JTextField();
        jBtnElgcConsultar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTxtElgcValorV = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jELGCTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 163, 194));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data");

        jTxtElgcDataV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtElgcDataVActionPerformed(evt);
            }
        });

        jBtnElgcConsultar.setBackground(new java.awt.Color(204, 204, 255));
        jBtnElgcConsultar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jBtnElgcConsultar.setForeground(new java.awt.Color(204, 204, 255));
        jBtnElgcConsultar.setText("CONSULTAR");
        jBtnElgcConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElgcConsultarActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Valor Total");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTxtElgcDataV, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTxtElgcValorV, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(jBtnElgcConsultar)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtElgcDataV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnElgcConsultar)
                    .addComponent(jTxtElgcValorV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jELGCTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jELGCTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtElgcDataVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtElgcDataVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtElgcDataVActionPerformed

    private void jBtnElgcConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElgcConsultarActionPerformed
// Verifica se ambos os campos de texto (valor e data) estão vazios.
        if (jTxtElgcValorV.getText().equals("") && jTxtElgcDataV.getText().equals("")) {
            // Se ambos estiverem vazios, obtém a lista completa de vendas e a define no controle.
            List lista = elgc_Vendas_DAO.listAll();
            elgc_VendasControle.setList(lista);
        } else {
            // Caso pelo menos um dos campos não esteja vazio.
            // Verifica se ambos os campos (valor e data) têm valores.
            if (!jTxtElgcValorV.getText().equals("") && !jTxtElgcDataV.getText().equals("")) {
                // Se ambos tiverem valores, converte a data e obtém a lista filtrada por data e valor.
                Date data = Util.strDate(jTxtElgcDataV.getText());
                List lista = elgc_Vendas_DAO.listDataValorVenda(data, Util.strDouble(jTxtElgcValorV.getText()));
                elgc_VendasControle.setList(lista);
            } else {
                // Se apenas um dos campos tem valor.
                // Verifica se o campo de valor não está vazio.
                if (!jTxtElgcValorV.getText().equals("")) {
                    // Se o campo de valor tiver valor, obtém a lista filtrada por valor.
                    List lista = elgc_Vendas_DAO.listValorVenda(Util.strDouble(jTxtElgcValorV.getText()));
                    elgc_VendasControle.setList(lista);
                } else {
                    // Se apenas o campo de data tem valor.

                    // Verifica se o campo de data não está vazio.
                    if (!jTxtElgcDataV.getText().equals("")) {
                        // Se o campo de data tiver valor, converte a data e obtém a lista filtrada por data.
                        Date data = Util.strDate(jTxtElgcDataV.getText());
                        List lista = elgc_Vendas_DAO.listDataVenda(data);
                        elgc_VendasControle.setList(lista);
                    }
                }
            }
        }

    }//GEN-LAST:event_jBtnElgcConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlg_elgcConsultaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlg_elgcConsultaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlg_elgcConsultaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlg_elgcConsultaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlg_elgcConsultaVendas dialog = new JDlg_elgcConsultaVendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnElgcConsultar;
    private javax.swing.JTable jELGCTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtElgcDataV;
    private javax.swing.JTextField jTxtElgcValorV;
    // End of variables declaration//GEN-END:variables
}
