package elgc_bean;
// Generated 05/12/2023 08:33:53 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ElgcVendas generated by hbm2java
 */
@Entity
@Table(name = "elgc_vendas",
        catalog = "db_evelin_centurion"
)
public class ElgcVendas implements java.io.Serializable {

    private int idelgcVendas;
    private ElgcCliente elgcCliente;
    private ElgcUsuarios elgcUsuarios;
    private Date elgcDataVenda;
    private Double elgcValortotalVenda;

    public ElgcVendas() {
    }

    public ElgcVendas(int idelgcVendas, ElgcCliente elgcCliente, ElgcUsuarios elgcUsuarios, Date elgcDataVenda, Double elgcValortotalVenda) {
        this.idelgcVendas = idelgcVendas;
        this.elgcCliente = elgcCliente;
        this.elgcUsuarios = elgcUsuarios;
        this.elgcDataVenda = elgcDataVenda;
        this.elgcValortotalVenda = elgcValortotalVenda;

    }

    @Id

    @Column(name = "idelgc_vendas", unique = true, nullable = false)
    public int getIdelgcVendas() {
        return this.idelgcVendas;
    }

    public void setIdelgcVendas(int idelgcVendas) {
        this.idelgcVendas = idelgcVendas;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fk_elgc_cliente", nullable = false)
    public ElgcCliente getElgcCliente() {
        return this.elgcCliente;
    }

    public void setElgcCliente(ElgcCliente elgcCliente) {
        this.elgcCliente = elgcCliente;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fk_elgc_usuario", nullable = false)
    public ElgcUsuarios getElgcUsuarios() {
        return this.elgcUsuarios;
    }

    public void setElgcUsuarios(ElgcUsuarios elgcUsuarios) {
        this.elgcUsuarios = elgcUsuarios;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "elgc_DataVenda", length = 10)
    public Date getElgcDataVenda() {
        return this.elgcDataVenda;
    }

    public void setElgcDataVenda(Date elgcDataVenda) {
        this.elgcDataVenda = elgcDataVenda;
    }

    @Column(name = "elgc_ValortotalVenda", precision = 22, scale = 0)
    public Double getElgcValortotalVenda() {
        return this.elgcValortotalVenda;
    }

    public void setElgcValortotalVenda(Double elgcValortotalVenda) {
        this.elgcValortotalVenda = elgcValortotalVenda;
    }

}
