package elgc_bean;
// Generated 05/12/2023 08:33:53 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ElgcUsuarios generated by hbm2java
 */
@Entity
@Table(name = "elgc_usuarios",
        catalog = "db_evelin_centurion"
)
public class ElgcUsuarios implements java.io.Serializable {

    private int idelgcUsuarios;
    private String elgcNome;
    private String elgcSenha;
    private int elgcNivel;
    private String elgcAtivo;

    public ElgcUsuarios() {
    }

    public ElgcUsuarios(int idelgcUsuarios, String elgcNome, String elgcSenha, int elgcNivel, String elgcAtivo) {
        this.idelgcUsuarios = idelgcUsuarios;
        this.elgcNome = elgcNome;
        this.elgcSenha = elgcSenha;
        this.elgcNivel = elgcNivel;
        this.elgcAtivo = elgcAtivo;
    }

    @Id

    @Column(name = "idelgc_usuarios", unique = true, nullable = false)
    public int getIdelgcUsuarios() {
        return this.idelgcUsuarios;
    }

    public void setIdelgcUsuarios(int idelgcUsuarios) {
        this.idelgcUsuarios = idelgcUsuarios;
    }

    @Column(name = "elgc_nome", nullable = false, length = 45)
    public String getElgcNome() {
        return this.elgcNome;
    }

    public void setElgcNome(String elgcNome) {
        this.elgcNome = elgcNome;
    }

    @Column(name = "elgc_senha", nullable = false, length = 45)
    public String getElgcSenha() {
        return this.elgcSenha;
    }

    public void setElgcSenha(String elgcSenha) {
        this.elgcSenha = elgcSenha;
    }

    @Column(name = "elgc_nivel", nullable = false)
    public int getElgcNivel() {
        return this.elgcNivel;
    }

    public void setElgcNivel(int elgcNivel) {
        this.elgcNivel = elgcNivel;
    }

    @Column(name = "elgc_ativo", nullable = false, length = 2)
    public String getElgcAtivo() {
        return this.elgcAtivo;
    }

    public void setElgcAtivo(String elgcAtivo) {
        this.elgcAtivo = elgcAtivo;
    }
    
    @Override
    public boolean equals(Object object) {// Sobrescreve o método equals para comparar a igualdade entre objetos ElgcUsuarios

        if (object instanceof ElgcUsuarios) {// Verifica se o objeto passado é uma instância de ElgcUsuarios

            ElgcUsuarios elgcUsuarios = (ElgcUsuarios) object;// Converte o objeto para a classe ElgcUsuarios

            if (this.getIdelgcUsuarios()== elgcUsuarios.getIdelgcUsuarios()) {// Compara os IDs para verificar a igualdade

                return true;// Retorna true se os IDs forem iguais
            }
        }
        return false; // Retorna false se o objeto não for uma instância de ElgcGruposalgado ou se os IDs não forem iguais
    
    }    
    

}
