package elgc_bean;
// Generated 15/12/2023 13:47:49 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ElgcCliente generated by hbm2java
 */
@Entity
@Table(name="elgc_cliente"
    ,catalog="db_evelin_centurion"
)
public class ElgcCliente  implements java.io.Serializable {


     private int idelgcCliente;
     private String elgcNome;
     private String elgcCpf;
     private String elgcRg;
     private String elgcBairro;
     private String elgcRua;
     private String elgcNumero;
     private String elgcCep;
     private String elgcSexo;
     private String elgcApelido;
     private String elgcObservacoes;
     private Date elgcDatanascimento;
     private String elgcTelefonefixo;
     private String elgcCelular;
     private String elgcEstadocivil;

    public ElgcCliente() {
    }

	
    public ElgcCliente(int idelgcCliente, String elgcNome, String elgcCpf, String elgcRg, String elgcBairro, String elgcRua, String elgcNumero, String elgcCep, String elgcSexo, String elgcApelido, String elgcObservacoes, Date elgcDatanascimento, String elgcTelefonefixo, String elgcCelular, String elgcEstadocivil) {
        this.idelgcCliente = idelgcCliente;
        this.elgcNome = elgcNome;
        this.elgcCpf = elgcCpf;
        this.elgcRg = elgcRg;
        this.elgcBairro = elgcBairro;
        this.elgcRua = elgcRua;
        this.elgcNumero = elgcNumero;
        this.elgcCep = elgcCep;
        this.elgcSexo = elgcSexo;
        this.elgcApelido = elgcApelido;
        this.elgcObservacoes = elgcObservacoes;
        this.elgcDatanascimento = elgcDatanascimento;
        this.elgcTelefonefixo = elgcTelefonefixo;
        this.elgcCelular = elgcCelular;
        this.elgcEstadocivil = elgcEstadocivil;
    }
   
     @Id 

    
    @Column(name="idelgc_cliente", unique=true, nullable=false)
    public int getIdelgcCliente() {
        return this.idelgcCliente;
    }
    
    public void setIdelgcCliente(int idelgcCliente) {
        this.idelgcCliente = idelgcCliente;
    }

    
    @Column(name="elgc_nome", nullable=false, length=45)
    public String getElgcNome() {
        return this.elgcNome;
    }
    
    public void setElgcNome(String elgcNome) {
        this.elgcNome = elgcNome;
    }

    
    @Column(name="elgc_cpf", nullable=false, length=45)
    public String getElgcCpf() {
        return this.elgcCpf;
    }
    
    public void setElgcCpf(String elgcCpf) {
        this.elgcCpf = elgcCpf;
    }

    
    @Column(name="elgc_rg", nullable=false, length=45)
    public String getElgcRg() {
        return this.elgcRg;
    }
    
    public void setElgcRg(String elgcRg) {
        this.elgcRg = elgcRg;
    }

    
    @Column(name="elgc_bairro", nullable=false, length=45)
    public String getElgcBairro() {
        return this.elgcBairro;
    }
    
    public void setElgcBairro(String elgcBairro) {
        this.elgcBairro = elgcBairro;
    }

    
    @Column(name="elgc_rua", nullable=false, length=45)
    public String getElgcRua() {
        return this.elgcRua;
    }
    
    public void setElgcRua(String elgcRua) {
        this.elgcRua = elgcRua;
    }

    
    @Column(name="elgc_numero", nullable=false, length=45)
    public String getElgcNumero() {
        return this.elgcNumero;
    }
    
    public void setElgcNumero(String elgcNumero) {
        this.elgcNumero = elgcNumero;
    }

    
    @Column(name="elgc_cep", nullable=false, length=45)
    public String getElgcCep() {
        return this.elgcCep;
    }
    
    public void setElgcCep(String elgcCep) {
        this.elgcCep = elgcCep;
    }

    
    @Column(name="elgc_sexo", nullable=false, length=45)
    public String getElgcSexo() {
        return this.elgcSexo;
    }
    
    public void setElgcSexo(String elgcSexo) {
        this.elgcSexo = elgcSexo;
    }

    
    @Column(name="elgc_apelido", nullable=false, length=45)
    public String getElgcApelido() {
        return this.elgcApelido;
    }
    
    public void setElgcApelido(String elgcApelido) {
        this.elgcApelido = elgcApelido;
    }

    
    @Column(name="elgc_observacoes", nullable=false, length=45)
    public String getElgcObservacoes() {
        return this.elgcObservacoes;
    }
    
    public void setElgcObservacoes(String elgcObservacoes) {
        this.elgcObservacoes = elgcObservacoes;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="elgc_datanascimento", nullable=false, length=10)
    public Date getElgcDatanascimento() {
        return this.elgcDatanascimento;
    }
    
    public void setElgcDatanascimento(Date elgcDatanascimento) {
        this.elgcDatanascimento = elgcDatanascimento;
    }

    
    @Column(name="elgc_telefonefixo", nullable=false, length=45)
    public String getElgcTelefonefixo() {
        return this.elgcTelefonefixo;
    }
    
    public void setElgcTelefonefixo(String elgcTelefonefixo) {
        this.elgcTelefonefixo = elgcTelefonefixo;
    }

    
    @Column(name="elgc_celular", nullable=false, length=45)
    public String getElgcCelular() {
        return this.elgcCelular;
    }
    
    public void setElgcCelular(String elgcCelular) {
        this.elgcCelular = elgcCelular;
    }

    
    @Column(name="elgc_estadocivil", nullable=false, length=45)
    public String getElgcEstadocivil() {
        return this.elgcEstadocivil;
    }
    
    public void setElgcEstadocivil(String elgcEstadocivil) {
        this.elgcEstadocivil = elgcEstadocivil;
    }


@Override
    public String toString() {// Sobrescreve o método toString para fornecer uma representação em String do objeto
        return this.getElgcNome();// Retorna o nome do produto como representação em String
    }

    @Override
    public boolean equals(Object object) {// Sobrescreve o método equals para comparar a igualdade entre objetos ElgcCliente (Classe)
        if (object instanceof ElgcCliente) {//Verifica se o objeto passado é uma instância de ElgcCliente
            ElgcCliente cliente = (ElgcCliente) object;// Converte o objeto para a classe ElgcCliente
            if (this.getIdelgcCliente() == cliente.getIdelgcCliente()) {// Compara os IDs para verificar a igualdade
                return true;// Retorna true se os IDs forem iguais
            }
        }
        return false;// Retorna false se o objeto não for uma instância de ElgcProduto ou se os IDs não forem iguais
    }


}


