package elgc_bean;
// Generated 15/12/2023 13:47:49 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ElgcGruposalgado generated by hbm2java
 */
@Entity
@Table(name="elgc_gruposalgado"
    ,catalog="db_evelin_centurion"
)
public class ElgcGruposalgado  implements java.io.Serializable {


     private int idelgcGruposalgado;
     private String elgcTiposalgado;
     private String elgcTipomassa;
     private String elgcTipocozimento;
     private int elgcRecheio;
     private double elgcQuantidade;

    public ElgcGruposalgado() {
    }

    public ElgcGruposalgado(int idelgcGruposalgado, String elgcTiposalgado, String elgcTipomassa, String elgcTipocozimento, int elgcRecheio, double elgcQuantidade) {
       this.idelgcGruposalgado = idelgcGruposalgado;
       this.elgcTiposalgado = elgcTiposalgado;
       this.elgcTipomassa = elgcTipomassa;
       this.elgcTipocozimento = elgcTipocozimento;
       this.elgcRecheio = elgcRecheio;
       this.elgcQuantidade = elgcQuantidade;
    }
   
     @Id 

    
    @Column(name="idelgc_gruposalgado", unique=true, nullable=false)
    public int getIdelgcGruposalgado() {
        return this.idelgcGruposalgado;
    }
    
    public void setIdelgcGruposalgado(int idelgcGruposalgado) {
        this.idelgcGruposalgado = idelgcGruposalgado;
    }

    
    @Column(name="elgc_tiposalgado", nullable=false, length=45)
    public String getElgcTiposalgado() {
        return this.elgcTiposalgado;
    }
    
    public void setElgcTiposalgado(String elgcTiposalgado) {
        this.elgcTiposalgado = elgcTiposalgado;
    }

    
    @Column(name="elgc_tipomassa", nullable=false, length=45)
    public String getElgcTipomassa() {
        return this.elgcTipomassa;
    }
    
    public void setElgcTipomassa(String elgcTipomassa) {
        this.elgcTipomassa = elgcTipomassa;
    }

    
    @Column(name="elgc_tipocozimento", nullable=false, length=45)
    public String getElgcTipocozimento() {
        return this.elgcTipocozimento;
    }
    
    public void setElgcTipocozimento(String elgcTipocozimento) {
        this.elgcTipocozimento = elgcTipocozimento;
    }

    
    @Column(name="elgc_recheio", nullable=false)
    public int getElgcRecheio() {
        return this.elgcRecheio;
    }
    
    public void setElgcRecheio(int elgcRecheio) {
        this.elgcRecheio = elgcRecheio;
    }

    
    @Column(name="elgc_quantidade", nullable=false)
    public double getElgcQuantidade() {
        return this.elgcQuantidade;
    }
    
    public void setElgcQuantidade(double elgcQuantidade) {
        this.elgcQuantidade = elgcQuantidade;
    }

@Override
    public String toString() {
        return this.getElgcTiposalgado();// Retorna o nome do produto como representação em String
    }

    
}

