package elgc_bean;
// Generated 15/12/2023 14:52:46 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ElgcVendasProduto generated by hbm2java
 */
@Entity
@Table(name="elgc_vendas_produto"
    ,catalog="db_evelin_centurion"
)
public class ElgcVendasProduto  implements java.io.Serializable {


     private int idelgcVendasProduto;
     private ElgcProduto elgcProduto;
     private ElgcVendas elgcVendas;
     private double elgcValoruni;
     private String elgcQuantidade;

    public ElgcVendasProduto() {
    }

    public ElgcVendasProduto(int idelgcVendasProduto, ElgcProduto elgcProduto, ElgcVendas elgcVendas, double elgcValoruni, String elgcQuantidade) {
       this.idelgcVendasProduto = idelgcVendasProduto;
       this.elgcProduto = elgcProduto;
       this.elgcVendas = elgcVendas;
       this.elgcValoruni = elgcValoruni;
       this.elgcQuantidade = elgcQuantidade;
    }
   
     @Id 

    
    @Column(name="idelgc_vendas_produto", unique=true, nullable=false)
    public int getIdelgcVendasProduto() {
        return this.idelgcVendasProduto;
    }
    
    public void setIdelgcVendasProduto(int idelgcVendasProduto) {
        this.idelgcVendasProduto = idelgcVendasProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_elgc_produto", nullable=false)
    public ElgcProduto getElgcProduto() {
        return this.elgcProduto;
    }
    
    public void setElgcProduto(ElgcProduto elgcProduto) {
        this.elgcProduto = elgcProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_elgc_vendas", nullable=false)
    public ElgcVendas getElgcVendas() {
        return this.elgcVendas;
    }
    
    public void setElgcVendas(ElgcVendas elgcVendas) {
        this.elgcVendas = elgcVendas;
    }

    
    @Column(name="elgc_valoruni", nullable=false, precision=22, scale=0)
    public double getElgcValoruni() {
        return this.elgcValoruni;
    }
    
    public void setElgcValoruni(double elgcValoruni) {
        this.elgcValoruni = elgcValoruni;
    }

    
    @Column(name="elgc_quantidade", nullable=false, length=45)
    public String getElgcQuantidade() {
        return this.elgcQuantidade;
    }
    
    public void setElgcQuantidade(String elgcQuantidade) {
        this.elgcQuantidade = elgcQuantidade;
    }




}


